### PR TITLE
KHR_mesh_compression extension

### PR DESCRIPTION
**Pull request by fanzhanggoogle**
Hi, I created this PR for reviewing and discussing before actually PR to glTF repo.

@ondys
@FrankGalligan

### CODE REVIEW

**Comment by ondys** [comment]
Do we want to name it KHR_mesh_compression or something more Draco specific ?  ..e.g.:

KHR_draco_mesh_compression

the thing is if we name it KHR_mesh_compression then it should be general enough for any compression algorithms that other people may want to add and Draco would have to be only a special case ..

**Comment by fanzhanggoogle** [comment]
@ondys I first thought about Draco specific, but then figured it might be better to have something more general like KHR_mesh_compression so that glTF could benefit more and glTF people will more likely to adopt it as an official extension. I think the design should be  general enough but not so sure. Still open to both options.

**Comment by ondys** [comment]
@fanzhanggoogle In the end this is something we should discuss with them. It's true that for glTF it may be better to create something universal.. I know that for example in OpenGL, every compression algorithm has its own extension, but the situation is somehow different there as the extensions define a texture format

Maybe we should send a quick email to Patrick for his opinion?

**Comment by FrankGalligan** [comment]
I think it would be good to make it more generic. But agree lets see what Patrick says.

**Comment by pjcozzi** [comment]
I don't have enough domain knowledge in compression to say for certain, but I suspect it would be hard to make a generic compression extension that turns out to be broadly useful for diverse compression techniques.  It would also increase the scope, and likely the timeline.  Perhaps go with `KHR_draco_mesh_compression` and later - if it proves valuable - a generic extension would be factored out of this.

**Pull request closed without merging**
